id: '414e96d9-5aec-461c-7a0f-08db36925815'
name: 'DataVault MSSQL'
description: 'DataVault MSSQL Example'
version: 'v1.9'
configuration:
  id: 'biGENIUS.Implementation.Generator.Datavault.Mssql'
  version: '1.10.0'
propertyValues: []
